### ISSUE TITLE
Do we need output/outcar in the HDF5 file?

### ISSUE THREAD

**Issue by sudarsan1989** [pyiron/pyiron_vasp#21]
A lot of the info is redundant and for example, the positions and forces are not sorted in the order of the structure. So this could be misleading. We could store the rest of the stuff you need into `output/generic/dft`. Thoughts @jan-janssen?

**Comment by jan-janssen** [comment]
`output/outcar` was introduced to include the output which is not available in the `vasprun.xml` file in particular the number of plane waves per kpoint and the energy correction based on the energy of a single atom. I guess these information are specific to VASP therefore I would not transfer them to `output/generic/dft`. But we can removed all redundant information - we only have to be sure that when importing from only and `OUTCAR` file all information are parsed correctly.

**Comment by sudarsan1989** [comment]
So now all redundant data has been cleaned up. https://github.com/pyiron/pyiron_vasp/pull/30
`output/outcar` still exists but contains only specific stuff (broyden mixing, plane waves etc)
