### ISSUE TITLE
Default value of SIGMA

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_vasp#25]
I see that SIGMA is not set in pyiron by default, so I presume that it takes the VASP default value of 0.2 eV, correct? Why is set_occupancy_smearing taking the default value of 0.1 eV?

**Comment by sudarsan1989** [comment]
I just used the default value for semiconductor systems. Will using 0.1 affect results for metals?

**Comment by samwaseda** [comment]
No I'm just confused that there's no tag by default (i.e. it takes the VASP default value of 0.2) but inside set_occupancy_smearing there's a different value written.

**Comment by sudarsan1989** [comment]
Yeah, that was written by me specific to the systems I use. If you want, I can change it to 0.2 eV as the default.

**Comment by jan-janssen** [comment]
I guess it should be consistent - therefore it should be changed to 0.2 - or am I missing something?

**Comment by samwaseda** [comment]
Yes I agree with Jan. I would be extremely confused if the value of SIGMA suddenly changes by putting an empty set_occupancy_spearing().

**Comment by samwaseda** [comment]
Oh shit maybe I should have made it clear that I was doing it XD
