### ISSUE TITLE
What is output/structure for?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_vasp#3]
Does output/structure have the final structure? It looks different for SPHInX

**Comment by jan-janssen** [comment]
https://github.com/pyiron/pyiron_vasp/blob/master/pyiron_vasp/vasp.py#L1028-1035 

The structure object which is stored in output/structure is the same like in input/structure - in SPHInX on the other hand a list of structures is stored - this should not be the case. Instead the structures should be generated on the fly. For this in output/generic/positions there should be a list of atomic positions.
